### ISSUE TITLE
Doesn't work with SpongeForge

### ISSUE THREAD

**Issue by pkej** [CJ-MC-Mods/OnlineUUIDMixin#2]
This mod doesn't work with [SpongeForge 1.12.2-2838-7.1.7-RC3902](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2). If your mod is enabled the server will simply skip loading SpongeForge. [Here's the output](https://gist.github.com/pkej/54d799b1352070a2304f048c67831e31) from starting up [Forge 14.23.5.2838](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.12.2.html) with the mod enabled. Only two mods is the SpongeForge and onlineuuids.

**Comment by cjm721** [comment]
Fixed via 5c406c9
